// Run only against the local, synthetic Development demo. No real child data.
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
const { chromium, webkit } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:5080';
assert.ok(['127.0.0.1', 'localhost'].includes(new URL(base).hostname), 'Use a local demo instance.');
await mkdir('artifacts/browser', { recursive: true });

for (const [name, engine] of [['chromium', chromium], ['webkit', webkit]]) {
  const browser = await engine.launch(name === 'chromium' && process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'de-DE', timezoneId: 'Europe/Berlin', deviceScaleFactor: 1 });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  const settle = async () => { await page.waitForLoadState('networkidle'); };
  const reportReady = async () => { await page.locator('#export-button:not([disabled])').waitFor(); await settle(); };
  const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name}: horizontal overflow`);
  try {
    await page.goto(base + '/Account');
    await page.getByRole('button', { name: 'Als Hausleitung starten' }).waitFor();
    await page.evaluate(() => document.fonts.ready);
    await noOverflow();
    await page.screenshot({ path: `artifacts/browser/${name}-login.png`, fullPage: true });
    await page.getByRole('button', { name: 'Als Hausleitung starten' }).click();
    await settle();
    assert.equal(await page.locator('.mobile-brand img').evaluate(e => e.complete && e.naturalWidth > 0), true);
    const token = `${name}-${Date.now()}`;
    await page.locator('[data-action="new-child"]').click();
    const form = page.locator('#child-form');
    await form.locator('[name="firstName"]').fill('Browserprobe');
    await form.locator('[name="lastName"]').fill(token);
    await form.locator('[name="birthDate"]').fill('2015-01-15');
    await form.locator('[name="gender"]').selectOption('Unspecified');
    await page.getByLabel('Staatsangehörigkeit hinzufügen').selectOption('DE');
    await form.locator('[name="contactName"]').fill('Erfundene Bezugsperson');
    await form.locator('[name="contactPhone"]').fill('+49 000 000000');
    await form.locator('[name="contactRelationship"]').fill('Testkontakt');
    await page.getByRole('button', { name: 'Speichern & heute erfassen' }).click();
    await page.locator('#child-dialog').waitFor({ state: 'hidden' });
    await page.getByLabel('Kind suchen').fill(token);
    const child = page.locator('.child-row').filter({ hasText: token });
    await child.locator('.presence-badge').waitFor();
    assert.match(await child.innerText(), /Heute erfasst/);
    assert.equal(await child.locator('a[href^="tel:"]').getAttribute('href'), 'tel:+49000000000');
    await child.locator('[data-undo]').click();
    await child.locator('[data-attend]').click();
    await child.locator('.presence-badge').waitFor();
    await noOverflow();
    // Delete only the synthetic profile just created, through the manager UI.
    await child.locator('.child-main > button').click();
    await page.locator('[data-action="delete-invalid"]').click();
    await page.locator('#confirm-action').click();
    await page.locator('#confirm-dialog').waitFor({ state: 'hidden' });
    await page.goto(base + '/Dashboard');
    await reportReady();
    await page.locator('[data-period="month"]').click();
    await reportReady();
    await page.locator('#open-filters').click();
    const filters = page.locator('#filter-form');
    await filters.locator('[name="site"][value="1"]').uncheck();
    await filters.locator('[name="site"][value="2"]').check();
    await filters.locator('[name="minAge"]').fill('10');
    await filters.locator('[name="maxAge"]').fill('14');
    await page.getByRole('button', { name: 'Auswertung anzeigen' }).click();
    await reportReady();
    await page.locator('[data-weekday="2"]').click();
    await reportReady();
    assert.match(await page.locator('#active-filters').innerText(), /Dienstag/);
    assert.match(await page.locator('#active-filters').innerText(), /Bottrop/);
    assert.match(await page.locator('#active-filters').innerText(), /10–14 Jahre/);
    const requestPromise = page.waitForRequest(r => r.url().endsWith('/api/reports/export'));
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#export-button').click();
    const exportRequest = await requestPromise;
    const payload = exportRequest.postDataJSON();
    assert.deepEqual(payload.siteIds, [2]);
    assert.equal(payload.minAge, 10); assert.equal(payload.maxAge, 14); assert.equal(payload.weekday, 2);
    const download = await downloadPromise;
    const xlsx = await readFile(await download.path());
    assert.equal(xlsx.subarray(0, 2).toString(), 'PK');
    await page.locator('[data-weekday="2"]').click();
    await reportReady();
    assert.ok(!(await page.locator('#active-filters').innerText()).includes('Dienstag'));
    // Exercise custom comparison, cancellation, then reset: hidden date inputs must not block submitting.
    await page.locator('#open-filters').click();
    await filters.locator('[name="comparison"]').selectOption('custom');
    await page.locator('[data-close="filter-dialog"]').click();
    await page.locator('#clear-all-filters').click();
    await reportReady();
    await page.locator('#open-filters').click();
    await page.getByRole('button', { name: 'Auswertung anzeigen' }).click();
    await page.locator('#filter-dialog').waitFor({ state: 'hidden' });
    await reportReady();
    await page.locator('[data-period="month"]').click();
    await reportReady();
    await page.evaluate(() => scrollTo(0, 0));
    await noOverflow();
    await page.screenshot({ path: `artifacts/browser/${name}-dashboard-mobile.png`, fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await noOverflow();
    await page.screenshot({ path: `artifacts/browser/${name}-dashboard-desktop.png`, fullPage: true });
    assert.deepEqual(errors, [], `${name}: browser errors`);
    console.log(`${name}: mobile CRUD, attendance, contact, chart filters, filter reset, Excel, branding and desktop layout passed.`);
  } finally { await context.close(); await browser.close(); }
}
